# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b140076627c2b8f1bc9e4697a6fd8e21695452074d332bd2c69f3704ae3a40fc77cee01fc1120b95d3e6081e64b7cd685ae4f66af5e4d01ac21907848a5b2f8

test:
  secret_key_base: 5a965d6ee2c64493bf3a980861a3afa1b1db63246f0486c28e1c5289f068867c6d8c96573802fb711ecc4e9b928595fb1732b16351713f83fe2cd5abcd278673

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
